version: '3'
services:
  server:
    image: "cristofercd/openmediaserver"
    ports:
     - "7890:7890"
    network_mode: "host"
    depends_on:
      - mariadb
  mariadb:
    image: "cristofercd/omediadb:test"
    ports:
      - "3306:3306"
    network_mode: "host"
