version: '3'
services:
  server:
    image: "cristofercd/omediaserver"
    ports:
     - "7890:7890"
    environment:
      - OMEDIADB_HOST=mariadb
    depends_on:
      - mariadb
  mariadb:
    image: "cristofercd/omediadb:test"
    ports:
      - "3306:3306"