version: '3'
services:
  server:
    image: "cristofercd/omediaserver:latest"
    ports:
     - "7890:7890"
    environment:
      - OMEDIADB_HOST=mariadb
      - OPENMEDIADB_TMDB_API=$OPENMEDIADB_TMDB_API
      - OPENMEDIADB_OMDB_API=$OPENMEDIADB_OMDB_API
    depends_on:
      - mariadb
  mariadb:
    image: "cristofercd/omediadb:test"
    ports:
      - "3306:3306"