CREATE TABLE Show (
	imdbId VARCHAR(15) PRIMARY KEY,
	name VARCHAR() NOT NULL,
	imgPoster VARCHAR(),
	imgBackground VARCHAR(),
	path VARCHAR()
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE Video (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	fileId INTEGER,
	imdbId VARCHAR(15) NOT NULL,
	name VARCHAR(),
	season INTEGER,
	episodeNumber INTEGER,
	sinopsis VARCHAR(),
	imgPoster VARCHAR(),

	FOREIGN KEY(imdbId) REFERENCES Show(imdbId)
		ON DELETE CASCADE ON UPDATE CASCADE,

	FOREIGN KEY(fileId) REFERENCES FileInfo(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE FileInfo (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	uri VARCHAR() NOT NULL,
	duration BIGINT,
	resolution VARCHAR(),
	bitrate VARCHAR(),
	codec VARCHAR()	
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE User (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR() NOT NULL,
	password CHAR(128) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE NotificationQueue (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	userId INTEGER PRIMARY KEY AUTO_INCREMENT,
	content VARCHAR() NOT NULL,

	FOREIGN KEY(userId) REFERENCES User(id)
		ON DELETE CASCADE ON UPDATE CASCADE
	
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE Session (
	id VARCHAR() PRIMARY KEY,
	userId INTEGER NOT NULL,
	expires DATE,
	
	FOREIGN KEY(userId) REFERENCES User(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE Following (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	userId INTEGER NOT NULL,
	showId VARCHAR(15) NOT NULL,

	FOREIGN KEY(userId) REFERENCES User(id)
		ON DELETE CASCADE ON UPDATE CASCADE
		
	FOREIGN KEY(showId) REFERENCES Show(imdbId)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE Seen (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	userId INTEGER NOT NULL,
	videoId INTEGER NOT NULL,

	FOREIGN KEY(userId) REFERENCES User(id)
		ON DELETE CASCADE ON UPDATE CASCADE
		
	FOREIGN KEY(videoId) REFERENCES Video(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;