CREATE DATABASE openMediaDB CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
USE openMediaDB;

CREATE TABLE `Show` (
	`imdbId` VARCHAR(15) PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`imgPoster` TEXT,
	`imgBackground` TEXT,
	`path` TEXT
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `FileInfo` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`uri` TEXT NOT NULL,
	`duration` BIGINT,
	`resolution` VARCHAR(20),
	`bitrate` VARCHAR(20),
	`codec` VARCHAR(20)	
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `Video` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`fileId` INTEGER,
	`imdbId` VARCHAR(15) NOT NULL,
	`name` VARCHAR(255),
	`season` INTEGER,
	`episodeNumber` INTEGER,
	`sinopsis` TEXT,
	`imgPoster` TEXT,

	FOREIGN KEY(`imdbId`) REFERENCES `Show`(`imdbId`)
		ON DELETE CASCADE ON UPDATE CASCADE,

	FOREIGN KEY(`fileId`) REFERENCES `FileInfo`(`id`)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `User` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`password` CHAR(128) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `NotificationQueue` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`userId` INTEGER,
	`content` TEXT NOT NULL,

	FOREIGN KEY(userId) REFERENCES `User`(id)
		ON DELETE CASCADE ON UPDATE CASCADE
	
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `Session` (
	`id` VARCHAR(128) PRIMARY KEY,
	`userId` INTEGER NOT NULL,
	`expires` DATE,
	
	FOREIGN KEY(userId) REFERENCES `User`(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `Following` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`userId` INTEGER NOT NULL,
	`showId` VARCHAR(15) NOT NULL,

	FOREIGN KEY(userId) REFERENCES `User`(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
		
	FOREIGN KEY(showId) REFERENCES `Show`(imdbId)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `Seen` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`userId` INTEGER NOT NULL,
	`videoId` INTEGER NOT NULL,

	FOREIGN KEY(userId) REFERENCES `User`(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
		
	FOREIGN KEY(videoId) REFERENCES `Video`(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
